application: myprettyshota
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /404.jpg
  static_files: static/default.jpg
  upload: static/default.jpg

- url: .*
  script: myprettyshota.app

- url: /logs
  script: myprettyshota.app
  login: admin

- url: /upload
  script: myprettyshota.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
